"""empty message

Revision ID: c8eb82a084b3
Revises: 
Create Date: 2021-06-16 14:04:02.107716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8eb82a084b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    op.drop_table('persons')
    op.drop_table('apartments')
    op.drop_table('posts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('posts_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('id_persona', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('district', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('comment', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('valoracion', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_persona'], ['persons.id'], name='posts_id_persona_fkey'),
    sa.PrimaryKeyConstraint('id', name='posts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('apartments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_persona', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('district', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_persona'], ['persons.id'], name='apartments_id_persona_fkey'),
    sa.PrimaryKeyConstraint('id', name='apartments_pkey')
    )
    op.create_table('persons',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('persons_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='persons_pkey'),
    sa.UniqueConstraint('email', name='persons_email_key'),
    sa.UniqueConstraint('name', name='persons_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('likes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_persona', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_post', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_persona'], ['persons.id'], name='likes_id_persona_fkey'),
    sa.ForeignKeyConstraint(['id_post'], ['posts.id'], name='likes_id_post_fkey'),
    sa.PrimaryKeyConstraint('id', name='likes_pkey')
    )
    # ### end Alembic commands ###
